[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/mmm"]

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # metadata

[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg" # auth rules

[[test.validator.clone]]
address = "CMTQqjzH6Anr9XcPVt73EFDTjWkJWPzH7H6DtvhHcyzV" # community-managed-token

[[test.validator.clone]]
address = "ocp4vWUzA2z2XMYJ3QhM9vWdyoyoQwAFJhRdVTbvo9E" # ocp: open_creator_protocol

[[test.validator.clone]]
address = "6Huqrb4xxmmNA4NufYdgpmspoLmjXFd3qEfteCddLgSz" # ocp: policy (allow all)

[[test.genesis]]
address = "migrxZFChTqicHpNa1CAjPcF29Mui2JU2q4Ym7qQUTi"
program = "tests/deps/mpl_migration_validator.so" # custom migration validator with only waiting period updated

[programs.localnet]
mmm = "cLawU4m5wgQ7nkwdkX6yRdkZ5NR6yN8dNuCmEiqTjk6"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
