[package]
name = "mmm"
version = "0.1.0"
description = "MMM is an open source and secure AMM protocol on Solana"
edition = "2018"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "mmm"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.27.0", features = ["init-if-needed"] }
anchor-spl = "0.27.0"
solana-program = "=1.14.17"
mpl-token-metadata = { version = "=1.10.0", features = ["no-entrypoint"] }
mpl-token-auth-rules = { version = "1.2.0", features = ["no-entrypoint"] }
spl-token = { version = "3.5.0",  features = ["no-entrypoint"] }
spl-associated-token-account = {version = "1.1.2", features = ["no-entrypoint"]}
